# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  akismet_key: '980ffb14cfd8'
  devise_key: ff05c74a3510be2605ef0a93892874122386ced0c51869244b24e579d63e6bbf4aa38a2de1029ab63386eb4a8f81f6a750e1e6a15fe96d70da3afa6178517227
  gmail_un: 'jrmy.ward@gmail.com'
  gmail_pw: 'Thehorriddeedisdone.'
  mail_chimp: ''
  mail_chimp_list: ''
  mail_chimp_webhook_token: ''
  secret_key_base: 56593a6eb18ae7ebd4559f2c5dbeeba1fce63724334011474a0aa5aa90f5134fa19422c8a5bb0778289f5044b1b6d3e0a408c999c2c491295db24ef4f6fe0b89
  stripe_api_key: ''
  stripe_public_key: ''
test:
  akismet_key: '980ffb14cfd8'
  devise_key: 240e81e2878684e967dda75c5ab2af8b3d382becb9805da02471f7395d828cd75a1dd0333067075aedbecc3b9f9b8a8bf4ccde252afc06e44d7dfa2cca8fdb94
  gmail_un: 'jrmy.ward@gmail.com'
  gmail_pw: 'Thehorriddeedisdone.'
  mail_chimp: ''
  mail_chimp_list: ''
  mail_chimp_webhook_token: ''
  secret_key_base: 7454b473da0dc2316753689646e3d331c7b4dc5de9d9194007b851352d4198f4bede969e32f45048014333ef75a0e422dd6aa231fd17139dd9a0b7055c556cb1
  stripe_api_key: ''
  stripe_public_key: ''
